/**
 * Showcase sample data — GENERATED from a real debate artifact.
 * Debate ID: 137f29ed-5eae-444e-97f1-ddcfa9e0ffcd
 * Motion: "Climate change is an existential threat"
 * Pro: Grok 4.3 (x-ai/grok-4.3), Con: Grok 4.20 (x-ai/grok-4.20)
 * Judge: gemini-3.1-flash-lite (google)
 * Fact-checker: gpt-5.4-mini (openai)
 * Generated: 2026-06-29
 *
 * ponytail: to regenerate, run a debate with `npm run debate:run`, export it,
 * then run `npx tsx scripts/_gen-sample-data.ts` (reads exports/_showcase-real.json).
 */
import type { DebateTurn, Model, FactCheck } from '@/types'

type TurnWithChecks = DebateTurn & { factChecks?: FactCheck[] }

const now = new Date('2026-06-29T23:13:36.117Z')

export const SAMPLE_MOTION = "Climate change is an existential threat"

export const sampleProModel: Model = {
  id: 'pro',
  name: "Grok 4.3",
  provider: 'openrouter',
  modelId: "x-ai/grok-4.3",
  isActive: true,
  crowdRating: 1640, crowdRatingDeviation: 150,
  aiQualityRating: 1695, aiQualityRatingDeviation: 140, aiQualityVolatility: 0.06,
  totalDebates: 64, wins: 38, losses: 20, ties: 6,
  createdAt: now, updatedAt: now,
}

export const sampleConModel: Model = {
  id: 'con',
  name: "Grok 4.20",
  provider: 'openrouter',
  modelId: "x-ai/grok-4.20",
  isActive: true,
  crowdRating: 1655, crowdRatingDeviation: 148,
  aiQualityRating: 1710, aiQualityRatingDeviation: 138, aiQualityVolatility: 0.06,
  totalDebates: 71, wins: 44, losses: 21, ties: 6,
  createdAt: now, updatedAt: now,
}

const fc = (
  id: string, turnId: string, claim: string, verdict: 'true' | 'false' | 'unverifiable',
  confidence: number, reasoning: string, sources: { url: string; snippet: string }[],
): FactCheck => ({ id, debateTurnId: turnId, claim, verdict, confidence, sources, reasoning, createdAt: now })

export const sampleTurns: TurnWithChecks[] = [
  {
    id: 't0',
    debateId: 'showcase',
    roundNumber: 1,
    side: 'pro',
    modelId: 'pro',
    reflection: "The debate is in its opening round with no prior arguments from the opponent. My central thesis is that climate change constitutes an existential threat to human civilization through irreversible environmental and societal collapse. No evidence has been presented yet; this statement will establish the foundation. The current state is neutral, awaiting my affirmative case.",
    critique: "Opponents may invoke false equivalence by equating climate risks with routine challenges or claim adaptation/tech will suffice without evidence. Anticipated weaknesses include underestimating tipping points or citing outdated models; I will preempt these with IPCC-aligned data and avoid overstatement.",
    speech: "Ladies and gentlemen, I affirm that climate change is an existential threat. IPCC reports confirm global temperatures have risen 1.1°C since pre-industrial levels, with accelerating ice melt and sea-level rise of 3.3 mm yearly threatening to displace hundreds of millions. Tipping points, including permafrost thaw and Amazon dieback, risk releasing gigatons of carbon, pushing warming beyond 2°C and rendering large regions uninhabitable. Extreme weather already disrupts agriculture, projecting food shortages for over a billion people by 2050 per UN estimates. Biodiversity collapse undermines ecosystems vital for human survival. While adaptation is possible in limited cases, it cannot avert systemic breakdown of economies and governance when habitable zones shrink. Peer-reviewed studies show inaction costs 20% of global GDP annually. This is not alarmism but recognition that unchecked emissions endanger organized society itself. Immediate transition to renewables is essential to preserve a viable future.",
    wordCount: 142,
    factChecksPassed: 3,
    factChecksFailed: 0,
    wasRejected: false,
    retryCount: 0,
    tokensUsed: 1749,
    latencyMs: 10460,
    createdAt: now,
    factChecks: [
      fc('f0_0', 't0', "IPCC reports confirm global temperatures have risen 1.1°C since pre-industrial levels", "true", 0.97,
        "The evidence supports the claim. IPCC-related sources state that current global temperature has risen by nearly 1.1°C relative to the 1850–1900 average, which is the standard pre-industrial baseline u",
        [{ url: "https://www.researchgate.net/publication/353777744_IPCC_climate_report_Earth_is_warmer_than_it's_been_in_125000_years", snippet: "The Earth's current surface temperature has increased by nearly 1.1 • C relative to the average temperature from 1850 to" },
          { url: "https://www.wri.org/insights/2023-ipcc-ar6-synthesis-report-climate-change-findings", snippet: "* Climate filter site by Climate. * Food filter site by Food. * Finance filter site by Finance. Already, with 1.1 degree" },
          { url: "https://www.ipcc.ch/sr15/chapter/chapter-1", snippet: "##### Special Report: Global Warming of 1.5 ºC. Understanding the impacts of 1.5°C global warming above pre-industrial l" },
          { url: "https://www.factcheck.org/2023/04/warming-beyond-1-5-c-harmful-but-not-a-point-of-no-return-as-biden-claims/", snippet: "FactCheck.org rated \"False\": If global warming goes above 1.5 C “we’re done; there’s no way to turn it around, according" }]),
      fc('f0_1', 't0', "accelerating ice melt and sea-level rise of 3.3 mm yearly threatening to displace hundreds of millions", "unverifiable", 0.76,
        "The evidence supports parts of the claim: sea level rise is accelerating, driven by melting glaciers and ice sheets, and it is around 3.3 mm per year in some past periods (though Source 2 says the rat",
        [{ url: "https://www.sciencedaily.com/releases/2026/05/260522023116.htm", snippet: "## Earth’s oceans are rising faster than ever, and scientists say the forces driving it are now impossible to ignore. : " },
          { url: "https://www.facebook.com/groups/1572893699951268/posts/2066590243914942", snippet: "The rate of rise has doubled: from 2.1 mm per year in 1993 to 4.5 mm per year by 2024. The practical implications are st" },
          { url: "https://www.weforum.org/stories/2025/03/rising-sea-levels-global-threat", snippet: "There are two main drivers of sea level rise: melting glaciers and seawater expansion due to rising global temperatures." }]),
      fc('f0_2', 't0', "Tipping points, including permafrost thaw and Amazon dieback, risk releasing gigatons of carbon", "true", 0.96,
        "The evidence directly supports the claim. Source 1 says abrupt permafrost thaw could release '10s to 100s of gigatonnes of carbon' into the atmosphere, and Source 2 discusses added carbon emissions fr",
        [{ url: "https://www.carbonbrief.org/guest-post-the-irreversible-emissions-of-a-permafrost-tipping-point", snippet: "# Guest post: The irreversible emissions of a permafrost ‘tipping point’. As global temperatures rise, this “permafrost”" },
          { url: "https://esd.copernicus.org/articles/16/565/2025", snippet: "We investigate the probabilities of triggering climate tipping points under five Shared Socioeconomic Pathways (SSPs) an" },
          { url: "https://www.reddit.com/r/science/comments/1k64v4i/high_probability_of_triggering_climate_tipping", snippet: "High probability of triggering climate tipping points under current policies, amplified by Amazon dieback and permafrost" }]),
      fc('f0_3', 't0', "extreme weather already disrupts agriculture", "true", 0.97,
        "The evidence directly supports the claim. Source 2 states that extreme heat is already causing major disruptions to global food and farming systems, affecting crops, livestock, fisheries, forests, and",
        [{ url: "https://www.weatherapi.com/", snippet: "{'location': {'name': 'Global', 'region': 'Maguindanao', 'country': 'Filipinas', 'lat': 7.3958, 'lon': 124.3069, 'tz_id'" },
          { url: "https://news.un.org/en/story/2026/04/1167352", snippet: "# Extreme heat pushing global food systems to the brink, UN agencies warn. Extreme heat is pushing global food and farmi" },
          { url: "https://www.instagram.com/reel/DXbS4KdCTES", snippet: "Sign up for Instagram to stay in the loop. Video by Food & Agriculture Organization of the United Nations on April 22, 2" }]),
      fc('f0_4', 't0', "projecting food shortages for over a billion people by 2050 per UN estimates", "unverifiable", 0.78,
        "The evidence supports the general idea that by 2050 the world may face major food security and resource scarcity challenges, and it mentions food insecurity in some regions. However, it does not clear",
        [{ url: "https://www.visionofhumanity.org/ten-billion-people-by-2050-poses-major-challenge-for-peace", snippet: "Projected high levels of population growth will collide with issues of resource scarcity and ecological threats in the f" },
          { url: "https://www.usda.gov/about-usda/news/blog/open-data-key-feeding-9-billion-people-2050", snippet: "“The UN estimates that about a quarter of arable land is currently severely degraded. And we are very much aware of limi" },
          { url: "https://www.sciencedirect.com/science/article/pii/S095937801930929X", snippet: "Majority forecasts for feeding the future global population predict an increase in a croplands at the expense of forests" }]),
    ],
  },
  {
    id: 't1',
    debateId: 'showcase',
    roundNumber: 1,
    side: 'con',
    modelId: 'con',
    reflection: "Opponent's central thesis: Climate change is an existential threat to humanity, citing IPCC data (1.1°C rise, 3.3mm/yr sea level rise), tipping points, food shortages for 1B+ by 2050, biodiversity loss, and 20% GDP annual cost. Strongest point is reference to peer-reviewed economic impacts and observable trends. Evidence is IPCC/UN heavy but selectively alarmist. Current state: Pro has set a high-emotion baseline equating warming with civilizational collapse; I must counter by reframing as manag",
    critique: "Opponent relies on appeal to authority (IPCC) and exaggerated projections without acknowledging uncertainty ranges or adaptation successes. \"Existential threat\" is hyperbolic—implies human extinction, yet no credible model predicts that. False dichotomy: claims adaptation \"cannot avert systemic breakdown\" while ignoring historical resilience. The 20% GDP figure is from older Stern Review outliers; updated models (e.g., Nordhaus, IMF) show far lower costs (2-4% GDP by 2100). Tipping point claims ",
    speech: "Ladies and gentlemen, I strongly oppose the motion. Climate change is a serious challenge, not an existential threat to humanity.\n\nWhile the IPCC reports 1.1°C warming, it also projects that even under high-emission scenarios, global GDP in 2100 will be far higher than today. Humans have adapted to far greater climate shifts throughout history. The Netherlands thrives below sea level through engineering; similarly, modern technology, nuclear power, desalination, and agricultural innovation can manage rising seas and changing weather.\n\nClaims of mass uninhabitability and billion-person famines ignore dramatic gains in crop yields from CO2 fertilization and GM technology. Bangladesh has reduced cyclone deaths by 99% despite sea-level rise through better warnings and infrastructure. Tipping points remain low-probability, high-uncertainty events per IPCC AR6.\n\nEconomic models by Nobel laureate William Nordhaus estimate optimal warming costs at roughly 2-4% of global GDP by 2100—not 20%. Humanity faces greater existential risks from nuclear war, engineered pandemics, and asteroid impacts. Mislabeling climate change as existential distracts from pragmatic solutions: innovation, adaptation, and advanced nuclear energy rather than panic-driven de-growth.\n\nWe will not end organized society. We will adapt and thrive, as we always have.",
    wordCount: 188,
    factChecksPassed: 5,
    factChecksFailed: 0,
    wasRejected: false,
    retryCount: 0,
    tokensUsed: 1503,
    latencyMs: 4357,
    createdAt: now,
    factChecks: [
      fc('f1_0', 't1', "Climate change is a serious challenge, not an existential threat to humanity.", "true", 0.89,
        "The evidence generally supports the claim. Multiple sources state that climate change is serious but not an existential threat or crisis to humanity in general, with one source explicitly saying it is",
        [{ url: "https://www.reddit.com/r/climatechange/comments/v19eeg/is_it_really_an_existential_crisis", snippet: "It is not an existential crisis yet, at least not for most of humanity. Humanity might still survive. climate change wil" },
          { url: "https://forum.effectivealtruism.org/posts/eJPjSZKyT4tcSGfFk/climate-change-is-in-general-not-an-existential-risk", snippet: "One of the big issues here is that climate change is percieved as posing an existential threat both to humanity generall" },
          { url: "https://www.forbes.com/sites/bobeccles/2025/08/19/heres-why-climate-change-is-actually-not-a-existential-crisis", snippet: "Two years ago I wrote about five climate change narratives (Scientific, Skeptical, Doomsday, Opportunistic, and Moral) a" }]),
      fc('f1_1', 't1', "The IPCC reports 1.1°C warming.", "true", 0.95,
        "The evidence shows the IPCC discussing a current global warming level of about 1.1°C, not claiming that the IPCC predicts 1.1°C as a future amount. Source 1 explicitly says 'Already, with 1.1 degrees ",
        [{ url: "https://www.wri.org/insights/2023-ipcc-ar6-synthesis-report-climate-change-findings", snippet: "* Climate filter site by Climate. * Food filter site by Food. * Finance filter site by Finance. Already, with 1.1 degree" },
          { url: "https://www.facebook.com/IPCC/posts/ipccs-synthesis-report-shows-that-continued-greenhouse-gas-emissions-will-lead-t/1084285647209161", snippet: "#IPCC’s Synthesis Report shows that continued greenhouse gas emissions will lead to increasing global warming, with the " },
          { url: "https://wmo.int/news/media-centre/climate-change-widespread-rapid-and-intensifying-ipcc", snippet: "Scientists are observing changes in the Earth’s climate in every region and across the whole climate system, according t" },
          { url: "https://www.factcheck.org/2023/04/warming-beyond-1-5-c-harmful-but-not-a-point-of-no-return-as-biden-claims/", snippet: "FactCheck.org rated \"False\": If global warming goes above 1.5 C “we’re done; there’s no way to turn it around, according" },
          { url: "https://www.factcheck.org/2018/03/smiths-error-filled-climate-op-ed/", snippet: "FactCheck.org rated \"False\": Wrote that climate scientists have predicted “global temperatures would increase more than " }]),
      fc('f1_2', 't1', "Even under high-emission scenarios, global GDP in 2100 will be far higher than today.", "true", 0.91,
        "The evidence supports the claim. Source 1 says global GDP could reach US$529 trillion by 2100 under a high-growth/emissions scenario, which is far above today's global GDP. Source 3 explicitly states ",
        [{ url: "https://archive.ipcc.ch/ipccreports/sres/emission/index.php?idp=101", snippet: "The 2.9% per year economic growth rate translates into a 25-fold expansion of global GDP that would reach US$529 trillio" },
          { url: "https://www.cbo.gov/publication/61146", snippet: "GDP will be at least 17 percent lower in 2100 than it. GDP will be at least 7 percent higher. There is an equal chance t" },
          { url: "https://climate.mit.edu/ask-mit/how-much-will-climate-change-affect-world-economy", snippet: "Because the world economy grows over time, even a future world that has lost 5% of GDP to climate change would be richer" }]),
      fc('f1_3', 't1', "Humans have adapted to far greater climate shifts throughout history.", "true", 0.92,
        "The evidence supports the claim. Source 1 from the Smithsonian describes climate effects on human evolution and implies humans survived and adapted to changing environments over time. Source 2 explici",
        [{ url: "https://humanorigins.si.edu/research/climate-and-human-evolution/climate-effects-human-evolution", snippet: "*   [Human Evolution Evidence](https://humanorigins.si.edu/evidence \"Evidence\")[Open submenu](https://humanorigins.si.ed" },
          { url: "https://www.globalcitizen.org/en/content/climate-change-lessons-from-history", snippet: "Humans have always developed societies around climate patterns — after all, the climate guides what we eat, what we wear" },
          { url: "https://plana.earth/academy/humans-have-not-always-adapted-climate-change", snippet: "Indeed, humanity has never disappeared, and climate change will not threaten the species' survival, at least not by the " }]),
      fc('f1_4', 't1', "The Netherlands thrives below sea level through engineering.", "true", 0.95,
        "The evidence supports the claim: the Netherlands has large areas below sea level and remains habitable largely because of extensive engineering such as the Delta Works, dams, sluices, and dikes. Sourc",
        [{ url: "https://news.mongabay.com/2023/03/sea-level-rise-looms-even-for-the-best-prepared-country-on-earth", snippet: "* *The Netherlands, a low-lying European country with more than a quarter of its land below sea level, has been going to" },
          { url: "https://www.swecogroup.com/topical/water/innovative-solutions-to-keep-the-netherlands-safe-from-flooding", snippet: "Home*/*Topical news*/*Water*/*Innovative solutions to keep the Netherlands safe from flooding. # Innovative solutions to" },
          { url: "https://www.instagram.com/p/DPYvaeAkcwp", snippet: "Across the low delta where two-thirds of the country sits below sea level, the Dutch built the Delta Works, a network of" }]),
    ],
  },
  {
    id: 't2',
    debateId: 'showcase',
    roundNumber: 2,
    side: 'pro',
    modelId: 'pro',
    reflection: "Opponent's central thesis: Climate change is serious but not existential, as adaptation, technology (nuclear, GM crops), and low costs (Nordhaus 2-4% GDP) allow humanity to thrive. Evidence includes IPCC 1.1°C, Netherlands/Bangladesh examples, CO2 fertilization, and AR6 on tipping points as low-probability. Strongest point: Historical adaptation and economic projections showing higher future GDP. Current state: Debate centers on whether impacts cross into civilizational threat or remain manageab",
    critique: "Opponent's argument relies on linear economic models that ignore non-linear tipping points (critiqued by Stern Review), overgeneralizes small-scale adaptation successes to global systemic risks, and selectively cites IPCC while downplaying high-impact scenarios. Internal tension: Claims \"far higher GDP\" assumes no feedbacks that could trigger collapse. Weak evidence on scalability of solutions against billion-scale displacement.",
    speech: "Ladies and gentlemen, the opposition underestimates systemic risks by highlighting localized adaptation like the Netherlands and Bangladesh. These successes cannot scale globally against multi-meter sea-level rise inundating megacities and shrinking arable land for billions. Nordhaus models, estimating 2-4% GDP costs, rely on linear assumptions and heavy discounting that exclude tipping points such as permafrost methane release and Amazon dieback, which IPCC AR6 identifies as amplifying warming beyond 2°C. Historical adaptation addressed gradual shifts, not rapid anthropogenic change projected to displace hundreds of millions and spark resource conflicts. CO2 fertilization gains are offset by extreme heat, droughts, and pests devastating tropical agriculture. While other existential risks exist, climate uniquely compounds them through governance breakdown and biodiversity collapse. Economic models ignoring catastrophic thresholds fail to capture threats to organized society. Mitigation remains essential to prevent irreversible disruption.",
    wordCount: 135,
    factChecksPassed: 3,
    factChecksFailed: 0,
    wasRejected: false,
    retryCount: 0,
    tokensUsed: 2773,
    latencyMs: 13333,
    createdAt: now,
    factChecks: [
      fc('f2_0', 't2', "The opposition underestimates systemic risks by highlighting localized adaptation like the Netherlands and Bangladesh.", "unverifiable", 0.73,
        "The evidence shows that the Netherlands and Bangladesh are examples of localized, long-term climate adaptation and flood-control planning, and it also notes that systemic climate risks are intensifyin",
        [{ url: "https://cwrrr.org/opinions/adaptation-strategies-water-governance-in-the-netherlands-bangladesh", snippet: "The Netherlands and Bangladesh prepared for climate adaptation through long-term planning, resulting in 'delta plans' wi" },
          { url: "https://ideas.repec.org/a/spr/masfgc/v31y2026i5d10.1007_s11027-026-10312-6.html", snippet: "Climate change adaptation has become a central concern for national governments as extreme weather events and systemic r" },
          { url: "https://www.preventionweb.net/news/netherlands-and-bangladesh-allies-flood-control-and-water-management", snippet: "Bangladesh and the Netherlands share one thing in common: both are situated in low-lying lands, making them prone to flo" }]),
      fc('f2_1', 't2', "The Netherlands and Bangladesh are examples of localized adaptation.", "unverifiable", 0.84,
        "The evidence shows Bangladesh being discussed in the context of locally-led adaptation, and it compares the Netherlands and Bangladesh in adaptation/water governance. However, it does not clearly stat",
        [{ url: "https://fuf.se/en/magasin/korrar/vad-kan-bangladesh-lara-nederlanderna-om-klimatanpassning", snippet: "The example from Bangladesh shows that it is not completely frictionless to run climate adaptation projects, not least b" },
          { url: "https://english.rvo.nl/subsidies-financing/lla", snippet: "Women in Bangladesh participating in a locally-led adaptation workgroup. Bangladesh: How Uttaran turns the tide. Uttaran" },
          { url: "https://cwrrr.org/opinions/adaptation-strategies-water-governance-in-the-netherlands-bangladesh", snippet: "The Dutch and Bangladesh deltas differ widely in water issues, socio-economic conditions and governance systems, as do t" }]),
      fc('f2_2', 't2', "Multi-meter sea-level rise would inundate megacities and shrink arable land for billions.", "true", 0.86,
        "The evidence supports the claim that substantial sea-level rise would inundate some megacities and cause major flooding risks. Source 1 notes up to 1.1 meters of sea-level rise by 2100 and large popul",
        [{ url: "https://earth.org/sea-level-rise-projections", snippet: "# Sea Level Rise Projections: 10 Cities at Risk of Flooding. **The Intergovernmental Panel on Climate Change (IPCC) fore" },
          { url: "https://www.reddit.com/r/Futurology/comments/1ncep32/by_2100_will_most_major_cities_be_abandoned_due", snippet: "Sea level is expected to rise by roughly half a meter by 2100. That is far from enough to make more than a few extreme c" },
          { url: "https://www.nature.com/articles/s41598-025-11517-6", snippet: "# Impacts of sea level rise and adaptation across Asia and the Pacific. This study applies a Coastal Flood Risk Modellin" }]),
      fc('f2_3', 't2', "Nordhaus models estimate 2-4% GDP costs.", "true", 0.91,
        "The evidence supports that Nordhaus-style models estimate GDP damages in the low single digits. Source 1 explicitly cites Nordhaus estimates of about 1% at 2°C, 2-3% at 3°C, and 4-9% at 4°C, which inc",
        [{ url: "https://docs.climateinteractive.org/projects/en-roads-reference-guide/en/latest/pages/damage.html", snippet: "We assessed the very low estimates (Nordhaus, 2007, 2013, and 2016; Weitzman, 2012), ranging from 1% at 2°C, 2-3% at 3°C" },
          { url: "https://evonomics.com/steve-keen-nordhaus-climate-change-economics", snippet: "*This piece is part of a series from Steve Keen,**Climate Change and the Nobel Prize in Economics: The Age of Rebellion*" },
          { url: "https://www.reddit.com/r/AskEconomics/comments/ct6q8x/what_did_nordhauss_estimate_for_the_social_cost", snippet: "First, Since GDP is a measure of both consumption and production, that is the variable that the model is calibrated upon" }]),
      fc('f2_4', 't2', "Nordhaus models rely on linear assumptions and heavy discounting.", "true", 0.93,
        "The evidence supports both parts of the claim. Source 1 explicitly says Nordhaus's use of discounting dramatically devalues future lives, and Source 3 shows DICE-2023 results varying substantially wit",
        [{ url: "https://www.taxresearch.org.uk/Blog/2025/12/16/economic-questions-the-william-nordhaus-question", snippet: "Third, Nordhaus's use of discounting dramatically devalues future lives. Keen argues that discounting future damage effe" },
          { url: "https://blogs.egu.eu/divisions/cl/2018/12/03/god-does-not-play-dice-but-bill-nordhaus-does-what-can-models-tell-us-about-the-economics-of-climate-change", snippet: "As explained above, a society's discount rate can be estimated from market interest rates. Knowing the economic growth, " },
          { url: "https://economics.yale.edu/sites/default/files/2024-03/barrage-nordhaus-2024-policies-projections-and-the-social-cost-of-carbon-results-from-the-dice-2023-model.pdf", snippet: "Social cost of carbon ($/tCO 2, 2019$) Scenario 2020 2025 2050 C/B optimal 50 59 125 T < 2 °C 75 89 213 T < 1.5 °C 3,557" }]),
    ],
  },
  {
    id: 't3',
    debateId: 'showcase',
    roundNumber: 2,
    side: 'con',
    modelId: 'con',
    reflection: "The central thesis of the PRO side remains that climate change poses an existential threat through tipping points, uninhabitability, food collapse, and systemic breakdown that adaptation cannot prevent. My CON thesis is that it is a manageable challenge, not existential, as humanity will adapt and GDP will grow. Evidence on both sides cites IPCC reports, Nordhaus models, historical adaptation, and tipping point probabilities. The strongest point made so far is PRO’s emphasis on IPCC-identified t",
    critique: "PRO’s argument relies on appeal to IPCC authority while selectively ignoring AR6’s own assessment that tipping points have “low to medium” confidence and are not projected to cause runaway warming this century under most scenarios. It creates a false dichotomy between “linear models” and catastrophe, ignoring that integrated assessment models do incorporate abrupt changes with limited impact on overall GDP projections. The claim of “multi-meter sea-level rise inundating megacities” by 2100 exagg",
    speech: "Ladies and gentlemen, my opponent exaggerates IPCC AR6 findings. While tipping points like permafrost thaw and Amazon dieback are noted, the report assigns them low-to-medium confidence of triggering runaway warming this century. Median sea-level rise projections remain under one meter by 2100, not the “multi-meter” catastrophe claimed. Nordhaus’s models are not purely linear; they incorporate uncertainty and still conclude optimal warming imposes only 2-4% GDP costs by 2100, with global GDP many times higher than today.\n\nHistorical adaptation was not always gradual. The Medieval Warm Period and Little Ice Age saw rapid regional shifts that societies survived through innovation. Today, crop yields have risen 20-30% partly due to CO2 fertilization; GM technology and precision agriculture counter heat and drought. Disaster deaths have plummeted 90%+ since 1920 thanks to technology, not despite climate change.\n\nClaims of inevitable governance collapse and resource wars ignore that wealthier societies are more resilient. Climate change is serious, yet dwarfed by risks like nuclear conflict or synthetic biology. Redirecting trillions toward panic-driven net-zero sacrifices adaptation funds and nuclear innovation that could decarbonize affordably.\n\nHumanity has thrived across ice ages and warm periods. We will adapt, innovate, and prosper. Climate change is a challenge to be managed, not an existential threat that ends organized society.\n\n(Word count: 238)",
    wordCount: 211,
    factChecksPassed: 4,
    factChecksFailed: 0,
    wasRejected: false,
    retryCount: 0,
    tokensUsed: 2035,
    latencyMs: 5391,
    createdAt: now,
    factChecks: [
      fc('f3_0', 't3', "IPCC AR6 notes tipping points like permafrost thaw and Amazon dieback.", "true", 0.74,
        "The evidence supports that IPCC AR6 discusses climate tipping points and feedbacks, and specifically references Amazon dieback and permafrost thaw as tipping-point-related issues. Source 1 says AR6 ha",
        [{ url: "https://climatetippingpoints.info/2021/10/31/ipcc-ar6-climate-tipping-points-feedbacks", snippet: "Clarity on Climate Tipping Points and Feedbacks. # What does the new IPCC report say about climate tipping points and fe" },
          { url: "https://esd.copernicus.org/articles/16/565/2025", snippet: "We investigate the probabilities of triggering climate tipping points under five Shared Socioeconomic Pathways (SSPs) an" },
          { url: "https://www.science.org/doi/10.1126/science.abn7950", snippet: "IPCC AR6 sometimes uses tipping point to refer to a class of abrupt change in which the subsequent rate of change is ind" }]),
      fc('f3_1', 't3', "The report assigns low-to-medium confidence to the possibility that tipping points like permafrost thaw and Amazon dieback will trigger runaway warming this century.", "unverifiable", 0.68,
        "The evidence does not identify a specific report or confirm that it assigns 'low-to-medium confidence' to runaway warming from permafrost thaw and Amazon dieback. Source 3 discusses probabilities of t",
        [{ url: "https://en.wikipedia.org/wiki/Tipping_points_in_the_climate_system", snippet: "# Tipping points in the climate system. In climate science, a **tipping point** is a critical threshold that, when cross" },
          { url: "https://climatetippingpoints.info", snippet: "Clarity on Climate Tipping Points and Feedbacks. # News Explainer: Is the AMOC closer to collapse than thought? The firs" },
          { url: "https://esd.copernicus.org/articles/16/565/2025/esd-16-565-2025.pdf", snippet: "2.3 Carbon tipping elements model We introduce the simple, system-dynamics-type model CTEM to investigate the carbon emi" }]),
      fc('f3_2', 't3', "Median sea-level rise projections remain under one meter by 2100.", "true", 0.93,
        "The evidence supports that median sea-level rise projections stay below 1 meter by 2100. NASA’s IPCC AR6 projection tool explicitly refers to median projections, and the MIT source notes scenarios ran",
        [{ url: "https://climate.mit.edu/ask-mit/what-are-best-and-worst-case-scenarios-sea-level-rise", snippet: "# What are the best- and worst-case scenarios for sea level rise? ###### *By 2100, we could see as little as 8 inches of" },
          { url: "https://www.ipcc.ch/srocc/chapter/chapter-4-sea-level-rise-and-implications-for-low-lying-islands-coasts-and-communities", snippet: "#### FAQ 4.1: What challenges does the inevitability of sea level rise present to coastal communities and how can commun" },
          { url: "https://sealevel.nasa.gov/ipcc-ar6-sea-level-projection-tool", snippet: "[NASA](http://www.nasa.gov/ \"visit nasa.gov\")[Sea Level Change](https://sealevel.nasa.gov/). [](https://sealevel.nasa.go" },
          { url: "https://www.factcheck.org/2016/08/stein-over-the-top-on-sea-level-rise/", snippet: "FactCheck.org rated \"Exagerated\": Claims that global warming would cause sea levels to rise on average “not one yard but" }]),
      fc('f3_3', 't3', "Nordhaus’s models are not purely linear.", "true", 0.78,
        "The evidence indicates Nordhaus’s climate-economy work (DICE and related models) includes multiple components and extensions beyond a simple linear structure, such as climate and economic submodels, d",
        [{ url: "https://blogs.egu.eu/divisions/cl/2018/12/03/god-does-not-play-dice-but-bill-nordhaus-does-what-can-models-tell-us-about-the-economics-of-climate-change", snippet: "Climate: Past, Present & Future | God does not play DICE – but Bill Nordhaus does! # God does not play DICE – but Bill N" },
          { url: "https://www.independent.org/article/2018/10/19/three-surprises-about-nobel-laureate-nordhaus-model-of-climate-change", snippet: "The award was of particular interest to me because back in 2009 I published an article in *The Independent Review* offer" },
          { url: "https://www.nobelprize.org/uploads/2018/10/nordhaus-lecture.pdf", snippet: "The RICE model is the regional version (first in Nordhaus and Yang 1996); the PRICE or probabilistic model incorporates " }]),
      fc('f3_4', 't3', "Nordhaus’s models incorporate uncertainty.", "true", 0.97,
        "The evidence directly supports the claim. Source 1 states that Nordhaus’s probabilistic PRICE model 'incorporates uncertainty,' and Source 2 discusses Nordhaus’s DICE-2016R2 model presenting 'uncertai",
        [{ url: "https://www.nobelprize.org/uploads/2018/10/nordhaus-lecture.pdf", snippet: "The RICE model is the regional version (first in Nordhaus and Yang 1996); the PRICE or probabilistic model incorporates " },
          { url: "https://www.nber.org/system/files/working_papers/w22933/w22933.pdf", snippet: "NBER WORKING PAPER SERIES PROJECTIONS AND UNCERTAINTIES ABOUT CLIMATE CHANGE IN AN ERA OF MINIMAL CLIMATE POLICIES Willi" },
          { url: "https://www.colorado.edu/amath/sites/default/files/attached-files/repetto_easton_-dicemodel_uncertainty.pdf", snippet: "Sir Nicholas Stern, principal author of the Stern Review of the Economics of Climate Change for the British Treasury Dep" }]),
    ],
  },
  {
    id: 't4',
    debateId: 'showcase',
    roundNumber: 3,
    side: 'pro',
    modelId: 'pro',
    reflection: "The debate centers on whether climate change poses risks to organized human society itself. Opponent's thesis: it is manageable via adaptation and innovation, with low-probability tipping points, Nordhaus-modeled costs of 2-4% GDP, historical resilience, and superior adaptation metrics (crop yields, disaster deaths). Strongest opponent point is empirical adaptation success and economic projections showing continued GDP growth. Current state: opponent downplays tail risks and scalability limits; ",
    critique: "Opponent selectively cites IPCC AR6 \"low-to-medium confidence\" on tipping points while ignoring that even moderate probabilities of permafrost methane or Amazon dieback create non-linear, irreversible risks excluded from Nordhaus assumptions. Historical analogies fail against unprecedented speed and global scale. Local successes (Netherlands, Bangladesh) do not extrapolate to simultaneous megacity inundation and agricultural collapse for billions. GDP focus omits governance breakdown and conflic",
    speech: "Ladies and gentlemen, the opposition cites IPCC \"low-to-medium confidence\" on tipping points and Nordhaus models to claim manageable costs. Yet AR6 explicitly warns that even moderate probabilities of permafrost thaw or Amazon dieback trigger irreversible feedbacks exceeding 2°C, rendering linear economic projections unreliable. Nordhaus frameworks discount catastrophic thresholds and assume smooth adaptation impossible at planetary scale.\n\nLocalized successes in the Netherlands or Bangladesh cannot extend to simultaneous submersion of coastal megacities and tropical breadbaskets feeding billions. Historical climate shifts occurred with far smaller populations and slower rates than today's anthropogenic acceleration. While crop yields and disaster mortality have improved, extreme heat, drought, and pests already offset CO2 benefits in vulnerable regions, per UN projections of over a billion facing food insecurity by 2050.\n\nClimate change compounds every other risk through resource conflicts and institutional failure. Recognizing it as existential demands urgent mitigation to preserve habitable conditions, not reliance on unproven global adaptation. The evidence shows systemic breakdown is possible; organized society must act before thresholds close that option. (228 words)",
    wordCount: 170,
    factChecksPassed: 2,
    factChecksFailed: 1,
    wasRejected: false,
    retryCount: 0,
    tokensUsed: 2671,
    latencyMs: 9024,
    createdAt: now,
    factChecks: [
      fc('f4_0', 't4', "The opposition cites IPCC \"low-to-medium confidence\" on tipping points and Nordhaus models to claim manageable costs.", "unverifiable", 0.58,
        "The evidence does not clearly show that an opposition group specifically cites IPCC 'low-to-medium confidence' on tipping points and Nordhaus models to argue costs are manageable. Source 2 says climat",
        [{ url: "https://climate.ec.europa.eu/news-other-reads/news/five-things-you-should-know-about-climate-scenarios-2026-06-05_en", snippet: "[Skip to main content](https://climate.ec.europa.eu/news-other-reads/news/five-things-you-should-know-about-climate-scen" },
          { url: "https://www.polytechnique-insights.com/en/columns/geopolitics/ipcc-the-cost-of-stopping-climate-change", snippet: "The global cost of limiting warming to 2°C over the 21 st Century is lower than the global economic benefits of reducing" },
          { url: "https://cleantechnica.com/2026/02/04/how-climate-economics-got-the-risks-wrong", snippet: "The study argues that widely used economic models underestimate the risks of climate change because they smooth impacts " }]),
      fc('f4_1', 't4', "AR6 explicitly warns that even moderate probabilities of permafrost thaw or Amazon dieback trigger irreversible feedbacks exceeding 2°C.", "false", 0.79,
        "The evidence does not support the claim as stated. Source 1 says AR6 WG2 notes that 2°C warming could reduce permafrost extent by 5–20%, but it does not say AR6 'explicitly warns' that moderate probab",
        [{ url: "https://www.woodwellclimate.org/review-of-permafrost-science-in-ipccs-ar6-wg2", snippet: "If warming reaches 2°C, the AR6 WG2 reports that it could reduce permafrost extent by 5-20%. Limiting warming to 1.5°C w" },
          { url: "https://www.carbonbrief.org/significant-risk-of-amazon-forest-dieback-if-global-warming-overshoots-1-5c", snippet: "# ‘Significant’ risk of Amazon forest dieback if global warming overshoots 1.5C. Plants and forests‘Significant’ risk of" },
          { url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC8166174", snippet: "Rapid Arctic warming has intensified northern wildfires and is thawing carbon-rich permafrost. Carbon emissions from per" }]),
      fc('f4_2', 't4', "Nordhaus frameworks discount catastrophic thresholds and assume smooth adaptation impossible at planetary scale.", "unverifiable", 0.66,
        "The evidence suggests Nordhaus-style damage functions are smooth and quadratic, which can be read as not explicitly modeling catastrophic thresholds (Source 1). However, the provided sources do not sh",
        [{ url: "http://acdc2007.free.fr/keen19.pdf", snippet: "Since his damage function is simply this constant multiplied by the change in temperature squared, he asserts that GDP h" },
          { url: "https://pubmed.ncbi.nlm.nih.gov/28948221", snippet: "Here, I hypothesize that perturbations of Earth's carbon cycle lead to mass extinction if they exceed either a critical " },
          { url: "https://www.researchgate.net/publication/265785610_Catastrophic_Thresholds_A_Synthesis_of_Concepts_Perspectives_and_Applications", snippet: "Research reported in this feature identifies a convergence of interpretations regarding the threshold dynamics of comple" }]),
      fc('f4_3', 't4', "Localized successes in the Netherlands or Bangladesh cannot extend to simultaneous submersion of coastal megacities and tropical breadbaskets feeding billions.", "true", 0.86,
        "The evidence supports the claim's core idea: localized flood-related successes or adaptations in places like the Netherlands and Bangladesh do not imply that similar measures can prevent broader, simu",
        [{ url: "https://www.scidev.net/global/news/bangladesh-and-the-netherlands-to-share-flood-research-1", snippet: "Bangladesh and the Netherlands will work together to counter threat of severe floods." },
          { url: "https://www.tum.de/en/news-and-events/all-news/press-releases/details/dramatically-higher-sea-levels-in-some-places-due-to-sinking-land", snippet: "Coastal megacities such as Jakarta are particularly affected by land subsidence and the simultaneous rise in sea level. " },
          { url: "https://www.germanwatch.org/en/2754", snippet: "A comparison between Bangladesh and the Netherlands, which are both seriously affected by rising sea levels, illustrates" }]),
      fc('f4_4', 't4', "Historical climate shifts occurred with far smaller populations and slower rates than today's anthropogenic acceleration.", "true", 0.92,
        "The evidence supports the claim that modern human-driven climate change is occurring much faster than past natural climate shifts. NASA says humans have had the largest impact since 1950, and a source",
        [{ url: "https://www.washingtonpost.com/climate-environment/interactive/2026/climate-change-temperature-rate-accelerating", snippet: "The fastest warming period since 1880 occurred in the past 30 years, according to a Washington Post analysis of NASA dat" },
          { url: "https://science.nasa.gov/earth/climate-change/global-warming", snippet: "Though people have had the largest impact on our climate since 1950, natural changes to Earth's climate have also occurr" },
          { url: "https://climate.mit.edu/ask-mit/todays-climate-change-similar-natural-warming-between-ice-ages", snippet: "In other words, in the modern day, atmospheric carbon has risen about 100 times faster than when humans emerged from the" }]),
    ],
  },
  {
    id: 't5',
    debateId: 'showcase',
    roundNumber: 3,
    side: 'con',
    modelId: 'con',
    reflection: "Opponent's central thesis: Climate change poses an existential threat via tipping points, scaled failures of adaptation, food insecurity for billions, and compounding risks leading to systemic breakdown. Evidence cited includes IPCC AR6 warnings on feedbacks exceeding 2°C, Nordhaus model flaws, historical population differences, UN food insecurity projections, and institutional failure risks. Strongest point: Acknowledgment that even moderate-probability tipping points could trigger irreversible",
    critique: "Opponent commits a false dichotomy by framing adaptation and mitigation as mutually exclusive, ignoring that innovation enables both. They strawman Nordhaus models as purely linear while ignoring that even updated integrated assessment models (IAMs) incorporating fat-tail risks (e.g., Weitzman, Nordhaus 2018 updates) still project manageable damages under optimal policy, not civilizational collapse. The \"billion facing food insecurity by 2050\" is a vulnerability projection, not a deterministic f",
    speech: "Ladies and gentlemen, my opponent insists climate change is existential, citing AR6 tipping points and UN food projections. Yet AR6 assigns only low-to-medium confidence to runaway feedbacks this century. Median sea-level rise remains under one meter by 2100, manageable with Dutch-style engineering now affordable to growing economies.\n\nNordhaus and updated IAMs, even accounting for fat tails, project global GDP in 2100 many times today's levels, with climate damages at 2-4% under optimal policy. This is serious, not existential. Historical adaptation succeeded amid rapid regional shifts; today's wealth, satellites, GM crops, nuclear power, and desalination amplify resilience. Crop yields have risen dramatically despite warming, thanks partly to CO2 fertilization. Disaster deaths fell over 90% since 1920 through technology.\n\nThe claim that localized successes cannot scale ignores that richer societies adapt better. UN \"billion at risk\" figures reflect scenarios without continued innovation, not inevitable collapse. Climate compounds risks only if we divert resources from nuclear innovation and adaptation into panic-driven de-growth.\n\nHumanity survived ice ages, plagues, and wars. We will not perish from 2-3°C warming. Climate change is a serious engineering and economic challenge, best met with pragmatism, not existential fear that distorts priorities. Organized society will adapt, innovate, and thrive. The motion fails.\n\n(Word count: 238)",
    wordCount: 205,
    factChecksPassed: 1,
    factChecksFailed: 1,
    wasRejected: false,
    retryCount: 0,
    tokensUsed: 2591,
    latencyMs: 4412,
    createdAt: now,
    factChecks: [
      fc('f5_0', 't5', "AR6 assigns only low-to-medium confidence to runaway feedbacks this century.", "unverifiable", 0.34,
        "The evidence mentions cloud feedbacks and their uncertainty, but it does not clearly state that AR6 assigns only low-to-medium confidence to runaway feedbacks this century. None of the sources directl",
        [{ url: "https://andymaypetrophysicist.com/2023/04/25/the-mysterious-ar6-ecs-part-2-the-impact-of-clouds", snippet: "# The Mysterious AR6 ECS, Part 2, the Impact of Clouds. AR6 tells us that cloud feedbacks, to GHG surface warming, are t" },
          { url: "https://climatetippingpoints.info/2021/10/31/ipcc-ar6-climate-tipping-points-feedbacks", snippet: "Clarity on Climate Tipping Points and Feedbacks. # What does the new IPCC report say about climate tipping points and fe" },
          { url: "https://www.carbonbrief.org/in-depth-qa-the-ipccs-sixth-assessment-report-on-climate-science", snippet: "# In-depth Q&A: The IPCC’s sixth assessment report on climate science. The United Nations’ Intergovernmental Panel on Cl" }]),
      fc('f5_1', 't5', "Median sea-level rise remains under one meter by 2100.", "false", 0.97,
        "The claim says median sea-level rise remains under 1 meter by 2100. However, the evidence shows median projections can reach about 0.9 m with 5°C warming, and other projections reach up to 1.0 m or mo",
        [{ url: "https://en.wikipedia.org/wiki/Sea_level_rise", snippet: "# Sea level rise. Between 1901 and 2018, the average sea level rose by 15–25 cm (6–10 in), with an increase of 2.3 mm (0" },
          { url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC5127314", snippet: "With a 5 °C rise by 2100, sea level will rise rapidly, reaching 0.9 m (median), and 80% of the coastline will exceed the" },
          { url: "https://www.reddit.com/r/science/comments/1gwp1na/new_study_estimates_that_a_1meter_sea_level_rise", snippet: "New study estimates that a 1-meter sea level rise by 2100 would affect over 14 million people and $1 trillion worth of p" },
          { url: "https://www.factcheck.org/2016/08/stein-over-the-top-on-sea-level-rise/", snippet: "FactCheck.org rated \"Exagerated\": Claims that global warming would cause sea levels to rise on average “not one yard but" }]),
      fc('f5_2', 't5', "Dutch-style engineering is now affordable to growing economies.", "unverifiable", 0.73,
        "The evidence shows that the Netherlands has strong engineering capability and a distinct engineering/economics tradition, and that engineering helps economies grow. However, none of the sources state ",
        [{ url: "https://www.forbes.com/sites/lauriewinkless/2016/09/26/its-official-engineering-helps-economies-to-grow", snippet: "Sweden, Denmark and the Netherlands top the new Engineering Index, but the U.S. and UK still lag behind." },
          { url: "https://www.tandfonline.com/doi/full/10.1080/09672567.2025.2492316", snippet: "The purpose of this paper is to explore the econo-engineering tradition in The Netherlands by analysing this new discipl" },
          { url: "https://www.raeng.org.uk/publications/reports/engineering-and-economic-growth-a-global-view", snippet: "Sweden, Denmark and the Netherlands top the list of countries by engineering strength in the new Engineering Index, with" }]),
      fc('f5_3', 't5', "Nordhaus and updated IAMs, even accounting for fat tails, project global GDP in 2100 many times today's levels.", "unverifiable", 0.68,
        "The evidence shows Nordhaus worked on climate-economy modeling and that some discussions consider catastrophic fat-tail risks, but it does not clearly state that Nordhaus and updated IAMs project glob",
        [{ url: "https://www.hks.harvard.edu/sites/default/files/centers/mrcbg/files/FWP_2020-04.pdf", snippet: "can truncate a fat tail merit serious consideration. In a recent paper, Nordhaus applies his thinking to account for a c" },
          { url: "https://www.facebook.com/nobelprize/videos/the-globe-at-centurys-end-will-be-vastly-different-from-today-in-his-2018-banque/1249448430508479", snippet: "Nordhaus was awarded the 2018 prize in economic sciences for integrating climate change into long-run macroeconomic anal" },
          { url: "https://www.cbo.gov/system/files/2025-02/61186-Climate-GDP.pdf", snippet: "The studies that appear in Nordhaus and Moffat (2017) overlap little with the ones we use; they include older studies, o" }]),
      fc('f5_4', 't5', "Nordhaus and updated IAMs project climate damages at 2-4% under optimal policy.", "true", 0.9,
        "Source 1 directly supports the claim: the DICE-2023 model (an updated IAM by Nordhaus) reports that the optimal cost-benefit program yields a damage-output ratio of 2.3% in 2100, which falls within th",
        [{ url: "https://economics.yale.edu/sites/default/files/2024-03/barrage-nordhaus-2024-policies-projections-and-the-social-cost-of-carbon-results-from-the-dice-2023-model.pdf", snippet: "The C/B optimal program reduces damages by half compared to the current policy scenario, with a damage- output ratio of " },
          { url: "https://ideas.repec.org/p/osf/socarx/nc43k.html", snippet: "Here I develop recursive IAM frameworks to model uncertainty, learning, and concern for misspecification about damages. " },
          { url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC7540901", snippet: "The representation of economic climate damages in IAMs might be improved by more rigorous grounding in observed relation" }]),
    ],
  },
]

export interface SampleEvaluation {
  order: 'pro_first' | 'con_first' | 'consensus'
  winner: 'pro' | 'con' | 'tie'
  proScore: number
  conScore: number
  parseStatus: 'parsed'
  reasoning: string
}

export const sampleEvaluations: SampleEvaluation[] = [
  {
    order: 'pro_first', winner: 'con', proScore: 0, conScore: 0, parseStatus: 'parsed',
    reasoning: "The CON debater wins this debate by maintaining a more consistent and evidence-backed position. While the PRO debater correctly identifies the severity of climate change, they struggle to bridge the logical gap between 'serious environmental damage' and 'existential threat to organized society.' The",
  },
  {
    order: 'con_first', winner: 'con', proScore: 0, conScore: 0, parseStatus: 'parsed',
    reasoning: "The CON debater maintained a more consistent and logically sound position throughout the debate. By defining 'existential' as the end of organized society, CON successfully shifted the burden of proof onto PRO to demonstrate that climate change would lead to human extinction or total civilizational ",
  },
  {
    order: 'consensus', winner: 'con', proScore: 0, conScore: 0, parseStatus: 'parsed',
    reasoning: "Consensus winner from pro-first and con-first evaluations: con",
  },
]

export const sampleDivergence = {
  judgedWinner: 'con' as const,
  factualityWinner: 'con' as const,
  divergence: 'aligned' as const,
  proFactsTrue: 8,
  proFactsFalse: 1,
  proFactsUnverifiable: 6,
  conFactsTrue: 10,
  conFactsFalse: 1,
  conFactsUnverifiable: 4,
  note: 'Real artifact: the judged winner is also the factually stronger side — persuasion and truth are aligned.',
}

export const sampleTelemetry = {
  totalTokens: 13322,
  judgeTokens: 0, // judge tokens not in turn-level export
  factChecks: 30,
  factCheckSources: 95,
  rounds: 3,
  factCheckMode: 'standard' as const,
  judge: 'gemini-3.1-flash-lite (google, direct)',
  proProvider: 'openrouter / x-ai/grok-4.3',
  conProvider: 'openrouter / x-ai/grok-4.20',
}
